// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckGameFilesIntegrity(arg1, arg2) {
  return window['go']['main']['App']['CheckGameFilesIntegrity'](arg1, arg2);
}

export function CleanUp(arg1, arg2) {
  return window['go']['main']['App']['CleanUp'](arg1, arg2);
}

export function DeleteDamagedParts(arg1, arg2) {
  return window['go']['main']['App']['DeleteDamagedParts'](arg1, arg2);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadNecessaryParts(arg1, arg2) {
  return window['go']['main']['App']['DownloadNecessaryParts'](arg1, arg2);
}

export function ExtractNecessaryParts(arg1, arg2) {
  return window['go']['main']['App']['ExtractNecessaryParts'](arg1, arg2);
}

export function FetchGameFilesInfo(arg1) {
  return window['go']['main']['App']['FetchGameFilesInfo'](arg1);
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function Play(arg1, arg2) {
  return window['go']['main']['App']['Play'](arg1, arg2);
}

export function PlayWithoutAccount(arg1) {
  return window['go']['main']['App']['PlayWithoutAccount'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function Update() {
  return window['go']['main']['App']['Update']();
}
