// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HadSession() {
  return window['go']['main']['Auth']['HadSession']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['Auth']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['Auth']['Logout']();
}

export function Me(arg1) {
  return window['go']['main']['Auth']['Me'](arg1);
}

export function Refresh() {
  return window['go']['main']['Auth']['Refresh']();
}
