// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function HadSession():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<void>;

export function Me(arg1:string):Promise<main.User>;

export function Refresh():Promise<string>;
