// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetGameProfilePath(arg1:number):Promise<string>;

export function InitFS():Promise<void>;

export function InitGameProfileConfig(arg1:number,arg2:string):Promise<void>;

export function MkDirAll(arg1:string):Promise<void>;

export function ReadConfig():Promise<main.Config>;

export function ReadGameProfileConfig(arg1:number):Promise<main.GameProfileConfig>;

export function WriteConfig(arg1:main.Config):Promise<void>;

export function WriteGameProfileConfig(arg1:number,arg2:main.GameProfileConfig):Promise<void>;
