// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameProfilePath(arg1) {
  return window['go']['main']['FS']['GetGameProfilePath'](arg1);
}

export function InitFS() {
  return window['go']['main']['FS']['InitFS']();
}

export function InitGameProfileConfig(arg1, arg2) {
  return window['go']['main']['FS']['InitGameProfileConfig'](arg1, arg2);
}

export function MkDirAll(arg1) {
  return window['go']['main']['FS']['MkDirAll'](arg1);
}

export function ReadGameProfileConfig(arg1) {
  return window['go']['main']['FS']['ReadGameProfileConfig'](arg1);
}

export function ReadLauncherConfig() {
  return window['go']['main']['FS']['ReadLauncherConfig']();
}

export function WriteGameProfileConfig(arg1, arg2) {
  return window['go']['main']['FS']['WriteGameProfileConfig'](arg1, arg2);
}

export function WriteLauncherConfig(arg1) {
  return window['go']['main']['FS']['WriteLauncherConfig'](arg1);
}
