// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {main} from '../models';

export function PingMinecraftServer(arg1:string,arg2:number):Promise<types.PingResponse>;

export function RetrieveGameProfiles():Promise<Array<main.GameProfile>>;
