// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PingMinecraftServer(arg1, arg2) {
  return window['go']['main']['GameProfiler']['PingMinecraftServer'](arg1, arg2);
}

export function RetrieveGameProfiles() {
  return window['go']['main']['GameProfiler']['RetrieveGameProfiles']();
}
