name: Wails build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'InfinityLauncher.exe'
            platform: 'windows/amd64'
            os: 'windows-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set version from tag
        uses: LSVH/gha-replace-placeholders@v1
        with:
          include: |
              wails.json
          placeholders: |
              %infinitylauncher%VERSION%=${{ github.ref_name }}
        
      - name: Build wails
        uses: dAppServer/wails-build-action@v3
        id: build
        with:
          wails-version: "v2.9.2"
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          nsis: false
          go-version: '1.23'
